const data = [
  {
    username_ref: "AnujVyas77@gmail.com",
    quizName: "java",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",
    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas7697@gmail.com",
    quizName: "java",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",

    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas7697@gmail.com",
    quizName: "java1",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",
    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas77@gmail.com",
    quizName: "java",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",
    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas7697@gmail.com",
    quizName: "java",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",

    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas7697@gmail.com",
    quizName: "java1",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",
    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas77@gmail.com",
    quizName: "java",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",
    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas7697@gmail.com",
    quizName: "java",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",

    _class: "com.portal.models.user.UserDashBoard",
  },
  {
    username_ref: "AnujVyas7697@gmail.com",
    quizName: "java1",
    studentName: "Anuj Vyas",
    result: "10",
    attemptedQuestion: "5",
    correctAnswer: "2",
    totalQuestion: "20",
    _class: "com.portal.models.user.UserDashBoard",
  },
];

export default data;
